application: restmansys
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/images/favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest