application: restmansys
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images/favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /foundation
  static_dir: foundation

- url: /stylesheet
  static_dir: stylesheet

- url: /javascript
  static_dir: javascript

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest